language: ruby
rvm:
- 2.1.5
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: OByBG19LgnEGWBniNIobw5yic0znqRgrbEVSMzkGqqmbNUuA9WyFxv+zWTDGwbGqjJct+JiBPOOAWOUwUGeU23iHU9iOyiWVbe9/OxcYgGyIUMczRR4mA6HReCvC3PSO169Z9R3JhIIcAe+zRC0urgdPBEiTkaZNXTNSyLdT8ZM=
  app: contribution-checker
  on:
    branch: master
    rvm: 2.1.5
